name: Changelog Update Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  changelog-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for CHANGELOG update
        run: |
          if ! git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q 'CHANGELOG.md'; then
            echo "Changelog must be updated."
            exit 1
          fi
          echo "Changelog updated."
